#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

random_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=random_key --value="$random_key"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

setfacl -dR -m g:"www-data":rwX -m u:"$app":rwX "$install_dir/var/"
setfacl -R -m g:"www-data":rwX -m u:"$app":rwX "$install_dir/var/"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

registration=$(boolstr "$registration")

ynh_config_add --template="local.yaml" --destination="$install_dir/config/packages/local.yaml"

ynh_config_add --template="dot_env" --destination="$install_dir/.env"

#=================================================
# BUILD KIMAI2
#=================================================
ynh_script_progression "Building $app..."

ynh_composer_exec install --no-dev --optimize-autoloader --no-interaction
ynh_composer_exec require laminas/laminas-ldap

setfacl -dR -m g:"www-data":rwX -m u:"$app":rwX "$install_dir/var/"
setfacl -R -m g:"www-data":rwX -m u:"$app":rwX "$install_dir/var/"

#=================================================
# INSTALL KIMAI2
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
    ynh_exec_as_app "php$php_version" bin/console kimai:install -n
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
