#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

random_key=$(ynh_string_random --length=32)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=registration --value=$registration
ynh_app_setting_set --app=$app --key=random_key --value=$random_key

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
setfacl -dR -m g:"www-data":rwX -m u:$app:rwX "$install_dir/var/"
setfacl -R -m g:"www-data":rwX -m u:$app:rwX "$install_dir/var/"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=low --footprint=low

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD KIMAI2
#=================================================
ynh_script_progression --message="Building Kimai2..." --weight=1

ynh_install_composer --phpversion="$phpversion" --workdir="$install_dir" --install_args="--optimize-autoloader"
ynh_composer_exec --phpversion="$phpversion" --workdir="$install_dir" --commands="require laminas/laminas-ldap"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
setfacl -dR -m g:"www-data":rwX -m u:$app:rwX "$install_dir/var/"
setfacl -R -m g:"www-data":rwX -m u:$app:rwX "$install_dir/var/"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

if [ $registration -eq 1  ]
then
	registration="true"
else
	registration="false"
fi

ynh_add_config --template="../conf/local.yaml" --destination="$install_dir/config/packages/local.yaml"

chmod 400 "$install_dir/config/packages/local.yaml"
chown $app:$app "$install_dir/config/packages/local.yaml"

# Configure environement
ynh_add_config --template="../conf/.env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL KIMAI2
#=================================================
ynh_script_progression --message="Installing Kimai2..." --weight=1

pushd "$install_dir"
	ynh_exec_as $app php$phpversion bin/console kimai:install -n
popd

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP SSOWAT
#=================================================
#REMOVEME? ynh_script_progression --message="Configuring permissions..." --weight=1

#REMOVEME? ynh_permission_create --permission="teamlead"
#REMOVEME? ynh_permission_create --permission="admin"
#REMOVEME? ynh_permission_create --permission="super_admin" --allowed "$admin"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
